/* ИСКРА.DCI — fake fleet data */
const SPARKS = {
  a: [40, 55, 35, 70, 60, 45, 75, 58, 50, 62, 48, 68],
  b: [50, 85, 90, 88, 60, 40, 55, 42, 58, 46, 52, 49],
  c: [30, 42, 38, 48, 52, 45, 40, 55, 50, 44, 47, 41],
  d: [60, 65, 58, 72, 68, 75, 70, 66, 62, 69, 64, 71],
};
const DEVICES = [
  {
    id: 'spine-01.msk',
    ip: '10.0.1.1',
    status: 'ok',
    tags: ['spine', 'prod'],
    spark: SPARKS.a,
    cpu: 73,
    temp: 41,
    role: 'Spine',
    site: 'MSK-DC1',
  },
  {
    id: 'leaf-07.msk',
    ip: '10.0.2.7',
    status: 'warn',
    tags: ['leaf', 'drift'],
    spark: SPARKS.b,
    cpu: 88,
    temp: 57,
    role: 'Leaf',
    site: 'MSK-DC1',
  },
  {
    id: 'spine-02.msk',
    ip: '10.0.1.2',
    status: 'ok',
    tags: ['spine', 'prod'],
    spark: SPARKS.a,
    cpu: 61,
    temp: 39,
    role: 'Spine',
    site: 'MSK-DC1',
  },
  {
    id: 'leaf-03.msk',
    ip: '10.0.2.3',
    status: 'ok',
    tags: ['leaf', 'prod'],
    spark: SPARKS.c,
    cpu: 54,
    temp: 44,
    role: 'Leaf',
    site: 'MSK-DC1',
  },
  {
    id: 'border-01.spb',
    ip: '10.1.0.1',
    status: 'err',
    tags: ['border', 'crit'],
    spark: SPARKS.b,
    cpu: 0,
    temp: 0,
    role: 'Border',
    site: 'SPB-DC2',
  },
  {
    id: 'leaf-09.spb',
    ip: '10.1.2.9',
    status: 'off',
    tags: ['leaf', 'maint'],
    spark: SPARKS.c,
    cpu: 0,
    temp: 0,
    role: 'Leaf',
    site: 'SPB-DC2',
  },
  {
    id: 'spine-04.spb',
    ip: '10.1.1.4',
    status: 'ok',
    tags: ['spine', 'prod'],
    spark: SPARKS.d,
    cpu: 67,
    temp: 42,
    role: 'Spine',
    site: 'SPB-DC2',
  },
  {
    id: 'leaf-12.msk',
    ip: '10.0.2.12',
    status: 'warn',
    tags: ['leaf', 'drift'],
    spark: SPARKS.b,
    cpu: 81,
    temp: 53,
    role: 'Leaf',
    site: 'MSK-DC1',
  },
  {
    id: 'stor-01.msk',
    ip: '10.0.5.1',
    status: 'ok',
    tags: ['storage', 'prod'],
    spark: SPARKS.d,
    cpu: 48,
    temp: 38,
    role: 'Storage',
    site: 'MSK-DC1',
  },
  {
    id: 'stor-02.msk',
    ip: '10.0.5.2',
    status: 'ok',
    tags: ['storage', 'prod'],
    spark: SPARKS.a,
    cpu: 52,
    temp: 40,
    role: 'Storage',
    site: 'MSK-DC1',
  },
  {
    id: 'leaf-21.spb',
    ip: '10.1.2.21',
    status: 'ok',
    tags: ['leaf', 'prod'],
    spark: SPARKS.c,
    cpu: 59,
    temp: 43,
    role: 'Leaf',
    site: 'SPB-DC2',
  },
  {
    id: 'mgmt-01.msk',
    ip: '10.0.0.1',
    status: 'ok',
    tags: ['mgmt', 'prod'],
    spark: SPARKS.d,
    cpu: 35,
    temp: 36,
    role: 'Mgmt',
    site: 'MSK-DC1',
  },
];
const ISSUES = [
  { id: 'border-01.spb', reason: 'Потеря связи с устройством', status: 'err' },
  { id: 'leaf-07.msk', reason: 'Drift: BGP-конфигурация', status: 'warn' },
  { id: 'leaf-12.msk', reason: 'Drift: MTU расходится', status: 'warn' },
];
// reconciler diff rows (desired vs observed)
const DIFF = [
  { d: 'hostname: leaf-07.msk', o: 'hostname: leaf-07.msk', k: 'same' },
  { d: 'mtu: 9000', o: 'mtu: 1500', k: 'drift' },
  { d: 'bgp:', o: 'bgp:', k: 'same' },
  { d: '  asn: 65002', o: '  asn: 65002', k: 'same' },
  { d: '  neighbors: [10.0.1.1, 10.0.1.2]', o: '  neighbors: [10.0.1.1]', k: 'drift' },
  { d: 'vlan: 200', o: 'vlan: 200', k: 'same' },
  { d: 'state: synced', o: 'state: drift', k: 'drift' },
];
Object.assign(window, { DEVICES, ISSUES, DIFF });
