// @iskra-dci/tokens build — Style Dictionary (DTCG) → CSS variables + typed TS map.
//
// Output:
//   dist/tokens.css   :root (dark) + .theme-cold + .theme-warm
//   dist/index.js     { tokens, themes, tokenNames, cssVar }
//   dist/index.d.ts   typed surface
//   dist/tokens.json  resolved flat map (tooling / docs)
//
// Token names are emitted verbatim (e.g. --bg, --accent, --s1) to stay
// compatible with the existing colors_and_type.css contract. We deliberately
// avoid the `css` transformGroup so dimensions stay in px (no rem conversion).
import StyleDictionary from 'style-dictionary';
import { mkdirSync, readFileSync, writeFileSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, 'dist');
const TMP = join(DIST, '.tmp');
const BRANDS_DIR = join(ROOT, 'src/brands');

const TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css'];
const PRIMITIVES = 'src/primitives/**/*.json';
const SEMANTIC = 'src/semantic/**/*.json';

const notPalette = (t) => !t.filePath.includes('palette');
const inFile = (needle) => (t) => t.filePath.includes(needle);

function sd(source, files) {
  return new StyleDictionary({
    source,
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: { out: { transforms: TRANSFORMS, buildPath: TMP + '/', files } },
  });
}

const cssFile = (destination, selector, filter) => ({
  destination,
  format: 'css/variables',
  filter,
  options: { selector, outputReferences: false },
});

const flatFile = (destination, filter) => ({
  destination,
  format: 'json/flat',
  filter,
});

async function run() {
  rmSync(DIST, { recursive: true, force: true });
  mkdirSync(TMP, { recursive: true });

  // Base (dark / default) — palette excluded so :root matches the legacy contract.
  await sd([PRIMITIVES, SEMANTIC], [
    cssFile('root.css', ':root', notPalette),
    flatFile('base.flat.json', notPalette),
  ]).buildAllPlatforms();

  // Theme overrides — only the tokens redefined in each theme file.
  await sd([PRIMITIVES, SEMANTIC, 'src/themes/cold.json'], [
    cssFile('cold.css', '.theme-cold', inFile('cold.json')),
    flatFile('cold.flat.json', inFile('cold.json')),
  ]).buildAllPlatforms();

  await sd([PRIMITIVES, SEMANTIC, 'src/themes/warm.json'], [
    cssFile('warm.css', '.theme-warm', inFile('warm.json')),
    flatFile('warm.flat.json', inFile('warm.json')),
  ]).buildAllPlatforms();

  // White-label brand packs — accent re-tints applied via .brand-<name>,
  // composing on top of any theme. Discover every src/brands/*.json.
  const brandFiles = readdirSync(BRANDS_DIR).filter((f) => f.endsWith('.json'));
  const brandNames = brandFiles.map((f) => f.replace(/\.json$/, ''));
  for (const name of brandNames) {
    await sd([PRIMITIVES, SEMANTIC, `src/brands/${name}.json`], [
      cssFile(`brand-${name}.css`, `.brand-${name}`, inFile(`brands/${name}.json`)),
      flatFile(`brand-${name}.flat.json`, inFile(`brands/${name}.json`)),
    ]).buildAllPlatforms();
  }

  // ── Assemble tokens.css ──────────────────────────────────────────────────
  const read = (f) => readFileSync(join(TMP, f), 'utf8').trim();
  const header =
    '/* Искра.DCI design tokens — GENERATED by @iskra-dci/tokens (do not edit). */\n' +
    '/* Hard-Shell Minimal · single accent hue · root font-size is intentionally 14px. */\n\n';
  const brandCss = brandNames.map((n) => read(`brand-${n}.css`));
  const css =
    header +
    [read('root.css'), read('cold.css'), read('warm.css'), ...brandCss].join('\n\n') +
    '\n';
  writeFileSync(join(DIST, 'tokens.css'), css);

  // ── Assemble typed JS/TS surface ─────────────────────────────────────────
  const base = JSON.parse(read('base.flat.json'));
  const cold = JSON.parse(read('cold.flat.json'));
  const warm = JSON.parse(read('warm.flat.json'));
  const toVars = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => ['--' + k, v]));
  const tokens = toVars(base);
  const themes = { cold: toVars(cold), warm: toVars(warm) };
  const brands = Object.fromEntries(
    brandNames.map((n) => [n, toVars(JSON.parse(read(`brand-${n}.flat.json`)))]),
  );

  writeFileSync(join(DIST, 'tokens.json'), JSON.stringify(tokens, null, 2) + '\n');

  const js =
    '// GENERATED by @iskra-dci/tokens — do not edit.\n' +
    `export const tokens = ${JSON.stringify(tokens, null, 2)};\n\n` +
    `export const themes = ${JSON.stringify(themes, null, 2)};\n\n` +
    `export const brands = ${JSON.stringify(brands, null, 2)};\n\n` +
    'export const tokenNames = Object.keys(tokens);\n\n' +
    'export function cssVar(name, fallback) {\n' +
    "  const n = name.startsWith('--') ? name : '--' + name;\n" +
    '  return fallback == null ? `var(${n})` : `var(${n}, ${fallback})`;\n' +
    '}\n';
  writeFileSync(join(DIST, 'index.js'), js);

  const brandNameUnion = brandNames.length
    ? brandNames.map((n) => JSON.stringify(n)).join(' | ')
    : 'string';
  const dts =
    '// GENERATED by @iskra-dci/tokens — do not edit.\n' +
    `export type TokenName = ${Object.keys(tokens).map((k) => JSON.stringify(k)).join(' | ')};\n` +
    `export type BrandName = ${brandNameUnion};\n` +
    'export declare const tokens: Record<TokenName, string>;\n' +
    "export declare const themes: { cold: Partial<Record<TokenName, string>>; warm: Partial<Record<TokenName, string>> };\n" +
    'export declare const brands: Record<BrandName, Partial<Record<TokenName, string>>>;\n' +
    'export declare const tokenNames: TokenName[];\n' +
    'export declare function cssVar(name: TokenName | string, fallback?: string): string;\n';
  writeFileSync(join(DIST, 'index.d.ts'), dts);

  if (existsSync(TMP)) rmSync(TMP, { recursive: true, force: true });
  console.log(
    `@iskra-dci/tokens: built ${Object.keys(tokens).length} tokens + 2 theme maps + ${brandNames.length} brand pack(s).`,
  );
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
